DROP DATABASE IF EXISTS JobSiteDB;
CREATE DATABASE JobSiteDB;

USE JobSiteDB;


CREATE TABLE Login (
  id INT NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(20) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  Status BOOLEAN default false,
  UNIQUE KEY(UserName),
  PRIMARY KEY (id)
);

CREATE TABLE Employer (
  id INT NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(20) NOT NULL,
  CompanyName VARCHAR(20) NOT NULL,
  ContactInfo VARCHAR(20) NOT NULL,
  FOREIGN KEY (UserName) REFERENCES Login(UserName),
  PRIMARY KEY (id)
);

CREATE TABLE Skills (
  id INT NOT NULL AUTO_INCREMENT,
  Skill VARCHAR(20) NOT NULL,
  UNIQUE KEY(Skill),
  PRIMARY KEY (id)
);

CREATE TABLE Employee (
  id INT NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(20) NOT NULL,
  JobTitle VARCHAR(20) NOT NULL,
  ContactInfo VARCHAR(20) NOT NULL,
  Bio VARCHAR(255) NOT NULL DEFAULT "I'M A LOSSER",
  FOREIGN KEY (UserName) REFERENCES Login(UserName),
  PRIMARY KEY (id)
);

CREATE TABLE RTABLE (
  idEmployee INT NOT NULL,
  idSkills INT NOT NULL,
  FOREIGN KEY (idEmployee) REFERENCES Employee(id),
  FOREIGN KEY (idSkills) REFERENCES Skills(id)
);

CREATE TABLE Jobs (
  id INT NOT NULL AUTO_INCREMENT,
  JobTitle VARCHAR(20) NOT NULL,
  UNIQUE KEY(JobTitle),
  PRIMARY KEY (id)
);

SELECT * FROM Employee;